[project]
name = "practicaindividual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yimon0512-hub", email = "yimon0512@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
practicaindividual = "practicaindividual:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
